apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.properties: |
    spring.application.name=GitHub_Search_repo
    spring.data.redis.host=redis
    spring.data.redis.port=6379
    spring.data.redis.password=13289812
    spring.data.redis.timeout=60s
    spring.cache.type=redis
    spring.data.redis.ssl.enabled=false

    spring.r2dbc.url=r2dbc:postgresql://postgres:5432/testDB
    spring.r2dbc.username=admin
    spring.r2dbc.password=13289812

    # Circuit Breaker
    resilience4j.circuitbreaker.instances.githubService.registerHealthIndicator=true
    resilience4j.circuitbreaker.instances.githubService.slidingWindowSize=10
    resilience4j.circuitbreaker.instances.githubService.permittedNumberOfCallsInHalfOpenState=3
    resilience4j.circuitbreaker.instances.githubService.failureRateThreshold=50
    resilience4j.circuitbreaker.instances.githubService.waitDurationInOpenState=10s

    # Retry
    resilience4j.retry.instances.githubService.maxAttempts=3
    resilience4j.retry.instances.githubService.waitDuration=500ms

    # Rate Limiter
    resilience4j.ratelimiter.instances.githubService.limitForPeriod=10
    resilience4j.ratelimiter.instances.githubService.limitRefreshPeriod=1s

    management.endpoints.web.exposure.include=health,info,metrics,prometheus

    management.metrics.export.prometheus.enabled=true